name: Release

on:
  workflow_dispatch:
    inputs:
      module:
        description: "Maven Submodule to Release (e.g., module-a, module-b)"
        required: true
      releaseVersion:
        description: "Version to use for release."
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Version to use for next development cycle."
        required: true
        default: "X.Y.Z-SNAPSHOT"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Install Parent POM (Falls Lokal benötigt)
        run: mvn install -N || echo "Parent-POM bereits vorhanden oder wird aus Repo geladen."

      - name: Optionaler Parent-POM-Build und Deployment
        run: |
          if [ -f "parent/pom.xml" ]; then
            mvn clean install -pl parent -am
            mvn deploy -pl parent -am -DskipTests
          fi
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Release Selected Module
        run: |
          mvn -B clean release:prepare release:perform \
            -DpushChanges=false -DlocalCheckout=true \
            -DreleaseVersion=${{ github.event.inputs.releaseVersion }} \
            -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }} \
            -pl ${{ github.event.inputs.module }} -am

          git tag v${{ github.event.inputs.releaseVersion }}-${{ github.event.inputs.module }}
          git push origin v${{ github.event.inputs.releaseVersion }}-${{ github.event.inputs.module }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Release to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: "target/${{ github.event.inputs.module }}.jar"
          body_path: "RELEASELOG.md"
          fail_on_unmatched_files: true
          tag_name: v${{ github.event.inputs.releaseVersion }}-${{ github.event.inputs.module }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Pull Request for Next Snapshot
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore(release): Bump version of ${{ github.event.inputs.module }} to next snapshot"
          delete-branch: "true"
          branch: "release/${{ github.event.inputs.releaseVersion }}-${{ github.event.inputs.module }}"
          base: "main"
          title: "chore(release): Prepare next snapshot version for ${{ github.event.inputs.module }}"
          body: "Automated PR for next snapshot after ${{ github.event.inputs.module }} release ${{ github.event.inputs.releaseVersion }}"
          labels: "release,ignore-for-release"
          assignees: "befsch"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
